# Generated by Django 3.2.9 on 2021-12-13 00:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_icon_picker.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20211212_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='button_a',
        ),
        migrations.RemoveField(
            model_name='music',
            name='button_a_text',
        ),
        migrations.RemoveField(
            model_name='music',
            name='button_a_url',
        ),
        migrations.RemoveField(
            model_name='music',
            name='button_b',
        ),
        migrations.RemoveField(
            model_name='music',
            name='button_b_text',
        ),
        migrations.RemoveField(
            model_name='music',
            name='button_b_url',
        ),
        migrations.RemoveField(
            model_name='music',
            name='buttons_enabled',
        ),
        migrations.AddField(
            model_name='music',
            name='buttons',
            field=wagtail.core.fields.StreamField([('Buttons', wagtail.core.blocks.StructBlock([('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail_icon_picker.blocks.FontAwesomeIconPickerBlock(required=True)), ('button_text', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
