# Generated by Django 3.2.9 on 2021-12-16 21:57

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_color_panel.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20211216_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='heading',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='musicgrid',
            name='grid',
            field=wagtail.core.fields.StreamField([('Grid', wagtail.core.blocks.StructBlock([('grids', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail_color_panel.blocks.NativeColorBlock(default='#000000')), ('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('intro', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=60, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
