# Generated by Django 3.2.9 on 2021-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20211216_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicgrid',
            name='heading',
            field=models.TextField(null=True),
        ),
    ]
