# Generated by Django 3.2.9 on 2021-12-17 09:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_color_panel.blocks
import wagtail_icon_picker.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_musicgrid_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgrid',
            name='buttons',
            field=wagtail.core.fields.StreamField([('Buttons', wagtail.core.blocks.StructBlock([('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail_icon_picker.blocks.FontAwesomeIconPickerBlock(required=True)), ('button_text', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicgrid',
            name='grid',
            field=wagtail.core.fields.StreamField([('Grid', wagtail.core.blocks.StructBlock([('grids', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail_color_panel.blocks.NativeColorBlock(default='#000000')), ('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('intro', wagtail.core.blocks.TextBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=60, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
