# Generated by Django 3.2.9 on 2021-12-17 21:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_color_panel.blocks
import wagtail_icon_picker.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_musicgrid_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='body',
            field=wagtail.core.fields.StreamField([('ListBox', wagtail.core.blocks.StructBlock([('list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('subtext', wagtail.core.blocks.TextBlock(required=False)), ('listtext', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=False))]))), ('single_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_gallery', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('gallery_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicgrid',
            name='grid',
            field=wagtail.core.fields.StreamField([('Grid', wagtail.core.blocks.StructBlock([('grids', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('color', wagtail_color_panel.blocks.NativeColorBlock(default='#fafafa')), ('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('intro', wagtail.core.blocks.TextBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail_icon_picker.blocks.FontAwesomeIconPickerBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=60, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicindexpage',
            name='box',
            field=wagtail.core.fields.StreamField([('NavBox', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('color', wagtail_color_panel.blocks.NativeColorBlock(default='#072660')), ('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
