# Generated by Django 3.2.9 on 2021-12-29 14:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20211218_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='heading',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
