# Generated by Django 3.2.9 on 2021-12-09 11:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donateindexpage_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateindexpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='donateindexpage',
            name='list',
        ),
        migrations.AddField(
            model_name='donateindexpage',
            name='box',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
