# Generated by Django 3.2.9 on 2021-12-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('donate', '0003_auto_20211209_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateindexpage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
