# Generated by Django 3.2.9 on 2021-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20211210_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
