# Generated by Django 3.2.9 on 2021-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_alter_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
