# Generated by Django 3.2.9 on 2021-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_alter_donation_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='customer_email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='customer_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=6),
        ),
    ]
