# Generated by Django 3.2.9 on 2021-12-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_alter_donation_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='customer_email',
            field=models.EmailField(editable=False, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='customer_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.CharField(default=0, editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
