# Generated by Django 3.2.9 on 2021-11-30 12:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribeform_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribefield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='subscribe.subscribeform'),
        ),
        migrations.AlterField(
            model_name='subscribeform',
            name='confirmation_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
