# Generated by Django 3.2.9 on 2021-12-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0002_auto_20211213_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remote',
            old_name='body',
            new_name='heading',
        ),
    ]
