# Generated by Django 3.2.9 on 2021-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0006_remotevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('img', models.ImageField(upload_to='video_poster')),
            ],
        ),
    ]
