# Generated by Django 3.2.9 on 2021-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
