# Generated by Django 3.2.9 on 2021-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0008_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
