# Generated by Django 3.2.9 on 2021-12-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0009_alter_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotevideo',
            name='video_source',
            field=models.IntegerField(choices=[(1, 'Gateway 1'), (2, 'Gateway 2'), (3, 'Gateway P')], default=1),
        ),
    ]
