# Generated by Django 3.2.9 on 2021-12-10 20:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail_icon_picker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopsPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post Date')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkshopsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('box1_icon', wagtail_icon_picker.fields.IconField(max_length=70)),
                ('box1', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('box2_icon', wagtail_icon_picker.fields.IconField(max_length=70)),
                ('box2', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
