# Generated by Django 3.2.9 on 2021-12-10 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopspost',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0), verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='workshopspost',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='workshopspost',
            name='subheading',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workshopspost',
            name='date',
            field=models.DateField(verbose_name='Workshop Date'),
        ),
    ]
