# Generated by Django 3.2.9 on 2021-12-10 22:34

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20211210_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopspost',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopspost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
