# Generated by Django 3.2.9 on 2021-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20211210_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopspost',
            name='link_url',
            field=models.URLField(null=True),
        ),
    ]
