# Generated by Django 3.2.9 on 2021-12-10 23:28

from django.db import migrations
import wagtail_icon_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshopspost_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopsindexpage',
            name='box1_icon',
            field=wagtail_icon_picker.fields.IconField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='workshopsindexpage',
            name='box2_icon',
            field=wagtail_icon_picker.fields.IconField(blank=True, max_length=70, null=True),
        ),
    ]
