# Generated by Django 3.2.9 on 2021-11-19 15:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0003_auto_20211119_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='aboutbody',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='aboutcover',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='aboutheading',
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('aboutheading', models.CharField(max_length=250, null=True)),
                ('aboutbody', wagtail.core.fields.RichTextField(blank=True)),
                ('about_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='About Button Link')),
                ('aboutcover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
