# Generated by Django 3.2.9 on 2021-11-19 15:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0004_auto_20211119_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='About Button Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aboutbody',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aboutcover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aboutheading',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
