# Generated by Django 3.2.9 on 2021-11-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0005_auto_20211119_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='music_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Music Button Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='musiccover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='musicheading',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
