# Generated by Django 3.2.9 on 2021-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211119_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='aboutbody',
            new_name='about_body',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='aboutcover',
            new_name='about_cover',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='aboutheading',
            new_name='about_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='musicheading',
            new_name='contact_address',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='musiccover',
            new_name='music_cover',
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='googlemaps_embed',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='music_heading',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
