# Generated by Django 3.2.9 on 2021-11-22 12:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211122_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_address',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
