# Generated by Django 3.2.9 on 2021-11-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211123_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
