# Generated by Django 3.2.9 on 2021-11-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_mycustomsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomsettings',
            old_name='contact_form_page',
            new_name='contact_form',
        ),
    ]
