# Generated by Django 3.2.9 on 2021-12-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0015_auto_20211130_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='support_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Support Button Link'),
        ),
    ]
