# Generated by Django 3.2.9 on 2021-12-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_sitesettings_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='events_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Event Image'),
        ),
    ]
