# Generated by Django 3.2.9 on 2021-12-19 18:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0022_auto_20211217_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pathways',
            field=wagtail.core.fields.StreamField([('Pathway_Button', wagtail.core.blocks.StreamBlock([('pathway', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(Required=True, max_length=20)), ('page', wagtail.core.blocks.PageChooserBlock(Required=True))]))], block_counts={'pathway': {'max_num': 7}}, max_num=9))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='festival_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='music_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='support_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='workshops_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
    ]
