# Generated by Django 3.2.9 on 2021-12-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211219_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='pathways',
        ),
    ]
