# Generated by Django 3.2.9 on 2021-12-19 20:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_homepage_pathways'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pathways',
            field=wagtail.core.fields.StreamField([('pathway', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('text', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('Index', wagtail.core.blocks.IntegerBlock(default=1, required=True))]))], default=0),
            preserve_default=False,
        ),
    ]
