# Generated by Django 3.2.9 on 2021-12-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211219_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='spotify',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
