# Generated by Django 3.2.9 on 2021-12-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0027_auto_20211220_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Privacy Policy'),
        ),
    ]
