# Generated by Django 3.2.9 on 2021-12-02 12:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20211202_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutindexpage',
            name='heading',
        ),
        migrations.AlterField(
            model_name='aboutindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
