# Generated by Django 3.2.9 on 2021-12-18 12:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_auto_20211217_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlocationpage',
            name='body',
            field=wagtail.core.fields.StreamField([('StandardBox', wagtail.core.blocks.StructBlock([('standard', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('subtext', wagtail.core.blocks.TextBlock(required=False)), ('listtext', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=False))]))), ('single_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_gallery', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('gallery_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])))])))]))], blank=True, null=True),
        ),
    ]
