# Generated by Django 3.2.9 on 2021-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_alter_aboutlocationpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
