# Generated by Django 3.2.9 on 2021-12-29 14:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0027_alter_about_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
