# Generated by Django 3.2.9 on 2021-12-29 20:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0029_about_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='introbox',
            field=wagtail.core.fields.StreamField([('IntroBox', wagtail.core.blocks.StructBlock([('single', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('subtext', wagtail.core.blocks.TextBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(Required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
