# Generated by Django 3.2.9 on 2021-12-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('menus', '0002_menu_sub_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sub_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='title_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
    ]
